import Head from "next/head";

import { Box, Container, Stack } from "@mui/material";
import { useTheme } from "@mui/material/styles";

// import { Toast } from "@lunit/design-system";

import Navigation from "@/components/Navigation";
import MainBoard from "@/components/MainBoard";
import SidePanel from "@/components/SidePanel";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        disableGutters
        maxWidth={false}
        sx={{
          height: "100%",
        }}
      >
        <Navigation />
        <Stack
          direction="row"
          sx={{
            display: "flex",
            maxHeight: "calc(100% - 3.75rem)", // 3.75rem is Navigation's height
          }}
        >
          <MainBoard />
          <SidePanel />
          {/* TODO: unable to use now, should be used after implementing Toast component */}
          {/* <Toast>회원 정보가 업데이트되었음.</Toast> */}
        </Stack>
      </Container>
    </>
  );
}
