# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on: push

# List of jobs
jobs:
  deploy-staging:
    # Operating System
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./packages/design-system
    # Job steps
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get branch name
        id: branch-name
        run: |
          echo "::set-output name=value::$(echo ${GITHUB_REF_NAME} | tr / -)"

      - name: Install dependencies
        run: yarn
        working-directory: ${{ env.WORKDIR }}

      - name: Publish to Chromatic
        env:
          BRANCH_NAME: ${{ steps.branch-name.outputs.value }}
          CHROMATIC_APP_ID: "62d7d1f2efc8a1e364b5e5e8"
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: ${{ env.WORKDIR }}
