name: "Chromatic Deployment - Design System"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/chromatic.yml"
      - "packages/design-system/**"
      - "packages/design-system-icons/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/chromatic.yml"
      - "packages/design-system/**"
      - "packages/design-system-icons/**"

jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - uses: nrwl/nx-set-shas@v4

      - name: Nx Cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/nx
          key: ${{ github.repository }}-nx-${{ env.NX_BASE }}
          restore-keys: |
            ${{ github.repository }}-nx-

      - name: Install dependencies
        run: npm ci

      - name: Build design-system package and its dependencies
        run: npx nx build @lunit/design-system

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook:design-system

      - name: Comment preview link
        if: ${{ github.event_name == 'pull_request' }}
        uses: NejcZdovc/comment-pr@v2.0.0
        with:
          message: "Design System Storybook: ${{ steps.chromatic.outputs.storybookUrl }}"
          identifier: "PREVIEW_LINK_COMMENT"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
