name: "Deploy the icons storybook"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/icons-storybook.yml
      - packages/design-system-icons/**

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./packages/design-system-icons
      HOST: design-system-icons.d.lunit.io
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Build package
        run: npx nx build @lunit/design-system-icons

      - name: Build storybook
        run: npx nx build-storybook @lunit/design-system-icons

      - name: Deploy
        uses: lunit-io/csg-sd-gitops/git-actions/preview-frontend-provider@v1.3.0
        with:
          pfp-access-key: ${{ secrets.PFP_ACCESS_KEY }}
          pfp-secret-key: ${{ secrets.PFP_SECRET_KEY }}
          build-path: ${{ env.WORKDIR }}/storybook-static
          use-public-runner: true
