# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic Deployment - Icons"

# Event for the workflow
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/icons-chromatic.yml"
      - "packages/design-system-icons/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/icons-chromatic.yml"
      - "packages/design-system-icons/**"

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - uses: nrwl/nx-set-shas@v4

      - name: Nx Cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/nx
          key: ${{ github.repository }}-nx-${{ env.NX_BASE }}
          restore-keys: |
            ${{ github.repository }}-nx-

      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g., yarn, npm, pnpm
        run: npm ci

      - name: Build design-system-icons package
        run: npm run build:design-system-icons

        # 👇 Adds Chromatic as a step in the workflow
      - id: chromatic
        name: Publish design-system-icons to Chromatic
        uses: chromaui/action@latest
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_ICONS }}
          buildScriptName: build-storybook:design-system-icons

      - name: Comment preview link
        if: ${{ github.event_name == 'pull_request' }}
        uses: NejcZdovc/comment-pr@v2.0.0
        with:
          message: "Icons Storybook: ${{ steps.chromatic.outputs.storybookUrl }}"
          identifier: "ICONS_PREVIEW_LINK_COMMENT"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
